name: anime_world_tutorial

description: A new Flutter anime app built with BLoC and modern Flutter practices.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Animations
  graphql_flutter: ^5.1.2
  smooth_page_indicator: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # API and Networking
  http: ^1.2.0

  # Local Storage
  shared_preferences: ^2.2.2

  # Performance
  cached_network_image: ^3.3.1

  # Flutter Essentials
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
